### ISSUE TITLE
Migrate from JCenter

### ISSUE THREAD

**Issue by Taskmaster132** [googlesamples/easypermissions#322] opened 2021-03-22 00:55 UTC
JCenter will be closing down in May 2021.

This blog has instructions on how to migrate to a different maven repo:

https://jeroenmols.com/blog/2021/02/04/migratingjcenter/

**Comment by samtstern** [comment] 2021-03-22 10:02
This is a duplicate of #319

**Closed by samtstern** 2021-03-22 10:02 UTC
