### ISSUE TITLE
Dialog/View appears for fraction of a second when permission is denied with "never ask again"

### ISSUE THREAD

**Issue by TheKalpit** [googlesamples/easypermissions#130] opened 2017-06-15 20:41 UTC
Hi,

This is my indented implementation:
1. If permission is granted, do stuff.
2. If not, ask for permission.
3. If denied with "never ask again" checked, do nothing.

Now, first two cases are fine, but in third case, it's showing a subtle white screen (probably of the Dialog) for fraction of a second.

Here's the code:

    @AfterPermissionGranted(PERMISSION_GPS)
    private void requiredGpsPermission() {
        String[] perms = {Manifest.permission.ACCESS_FINE_LOCATION, Manifest.permission.ACCESS_COARSE_LOCATION};
        if (EasyPermissions.hasPermissions(this, perms)) {
            getLocation();
        } else {
                EasyPermissions.requestPermissions(this, getString(R.string.request_location_message), PERMISSION_GPS, perms);
        }
    }

I'm calling this method in onCreate(); of activity.

How to reproduce:
1. Launch activity (with the specified code).
2. Deny permission.
3. Launch again, this time deny with "Never ask again" checked.
4. Launch again. You should now see the issue.

**Comment by samtstern** [comment] 2017-06-16 16:14
@TheKalpit can you reproduce this with the sample app included in this repository?  I can't seem to make it happen.

**Comment by berviantoleo** [comment] 2017-08-08 09:06
@TheKalpit are you still have this issue? If yes, please attach your full code.

Anyway, I have a problem too when calling method with "AfterPermissionGranted" and implements "onPermissionDenied" with doing "Never ask again". That will raise looping call method with AfterPermissionGranted.

**Comment by samtstern** [comment] 2017-08-08 15:03
@berviantoleo you should check for "never ask again" only in "onPermissionDenied".

@TheKalpit I am closing this issue since there has not been a response in a few weeks.

**Closed by samtstern** 2017-08-08 15:03 UTC
