### ISSUE TITLE
after denied permission i get this error(In Fragment)

### ISSUE THREAD

**Issue by rezaiyan** [googlesamples/easypermissions#133] opened 2017-06-19 20:06 UTC
`

 FATAL EXCEPTION: main

 Process: co.iliasystem.akbarjoojeh, PID: 7204
 java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
     at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1842)
     at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1860)
     at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:650)
     at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:609)
     at android.support.v4.app.DialogFragment.show(DialogFragment.java:143)
     at ir.droidhub.permissionhelper.helper.BaseSupportPermissionsHelper.showRequestPermissionRationale(BaseSupportPermissionsHelper.java:30)
     at ir.droidhub.permissionhelper.helper.PermissionHelper.requestPermissions(PermissionHelper.java:73)
     at ir.droidhub.permissionhelper.EasyPermissions.requestPermissions(EasyPermissions.java:184)
     at ir.droidhub.permissionhelper.EasyPermissions.requestPermissions(EasyPermissions.java:155)
     at ir.droidhub.permissionhelper.EasyPermissions.requestPermissions(EasyPermissions.java:110)
     at co.iliasystem.akbarjoojeh.fragment.PayFragment.smsTask(PayFragment.java:313)
     at co.iliasystem.akbarjoojeh.fragment.PayFragment.access$400(PayFragment.java:54)
     at co.iliasystem.akbarjoojeh.fragment.PayFragment$3.onClick(PayFragment.java:284)
     at com.hamirt.hamidialog.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:337)
     at android.view.View.performClick(View.java:5637)
     at android.view.View$PerformClick.run(View.java:22429)
     at android.os.Handler.handleCallback(Handler.java:751)
     at android.os.Handler.dispatchMessage(Handler.java:95)
     at android.os.Looper.loop(Looper.java:154)
     at android.app.ActivityThread.main(ActivityThread.java:6119)

      at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

`

**Comment by samtstern** [comment] 2017-06-19 20:53
@rezaiyan what version of the library are you using?

**Comment by madhanmallow** [comment] 2017-06-21 19:38
The issue also happens to me. I used the version compile 'pub.devrel:easypermissions:0.4.0'

**Comment by SUPERCILEX** [comment] 2017-08-18 22:32
@madhanmallow See https://github.com/googlesamples/easypermissions/issues/150#issuecomment-322808647, it looks like it could be the same issue. It could also be that you're [not calling `super.onActivityResult(...)`](https://stackoverflow.com/a/30429551/4548500) in your activity. Though looking at your stack trace, I don't understand how it relates to the code you posted. It looks like you're trying to request the permissions from a dialog that's trying to close itself which would explain the state loss. I could try to help some more with additional info! 😄 

PS: looping the permission request infinitely until the user accepts your permission isn't the best UX. 😄

**Comment by samtstern** [comment] 2017-08-22 15:10
Since it's been a long time since the last response by @madhanmallow (my fault for not getting back after the Jun 21 comment) and this is likely a duplicate, let's call this a duplicate of #150 and move discussion over there.

**Closed by samtstern** 2017-08-22 15:10 UTC
