### ISSUE TITLE
Use in tablet the rationale is too large,even over screen.

### ISSUE THREAD

**Issue by GitABiao** [googlesamples/easypermissions#288] opened 2019-09-04 08:25 UTC
## Basic Information

Device type: _HUAWEI M6_
OS version: _Android 9_
EasyPermissions version: ____2.0.1____

## Describe the problem
The rationale is too large,even over screen.
What happened?  What did you expect to happen?

## Code and logs

```
// TODO(you): show the code that produces the problem,
//            and any relevant logs.
```

**Comment by samtstern** [comment] 2019-09-04 16:05
@GitABiao could you show a screenshot of how this looks on the device?

**Comment by GitABiao** [comment] 2019-09-06 08:29
It`s like this 
![Screenshot_20190906_161443_com abiao arouterdemo](https://user-images.githubusercontent.com/10267859/64412754-b034e480-d0c2-11e9-8321-442dbe7be9c0.jpg)

**Comment by VMadalin** [comment] 2019-09-09 08:55
@GitABiao Thank you for the screenshot attached, I tried to reproduce it on simulator forcing rotate screen but unfortunately was no been posible. The devices are Nexus 10 and Pixel C with similar screen resolution with Huawei M6 (2.560 x 1.600)
<img width="1181" alt="Screenshot 2019-09-09 at 10 27 17" src="https://user-images.githubusercontent.com/18151158/64516379-bc9d8500-d2ee-11e9-8f99-71d537204d63.png">

Could you trying to execute the sample project of this library, to discard posible errors with integration. You could reproduce the same error on a different tablet?

**Comment by androidlpf** [comment] 2019-09-20 11:54
click cancel

**Comment by samtstern** [comment] 2019-09-20 17:45
@GitABiao it would really help if you showed the code you're using to launch the problematic dialog.

**Comment by GitABiao** [comment] 2019-09-23 07:29
I have confirmed that the dialog created by Huawei M6 using Android api will also appear in the same situation I sent, it should not be a bug in this framework.

**Comment by VMadalin** [comment] 2019-09-23 07:38
@GitABiao That have a lot of sense, basically because the library use the `dialog` android component for display the rationale message dialog. Thank you for the clarification.

The only solution what I see there is to create a custom view for display, instead the dialog or create an optional callback on request permission method for giving the option to create the user any view their want for show the rationale message, but maybe this is out of scope of library.

**Closed** 2019-09-23 10:13 UTC
Labels: bug, needs-info

**Comment by samtstern** [comment] 2019-09-23 17:31
@GitABiao thank you for following up and confirming it wasn't something in our code!  I really appreciate it,
