### ISSUE TITLE
Problem with stack rationale dialog

### ISSUE THREAD

**Issue by mgolebiowski95** [googlesamples/easypermissions#193] opened 2018-01-09 09:23 UTC
## Basic Information

Device type: ________
OS version: ________
EasyPermissions version: 1.0.1

## Describe the problem

What happened?  What did you expect to happen?

When I executed code below code 0 in onStart() every  time show new rationale dialog over previous dialog. If dialog is exist new dialog should'nt show. A good solution would be to add a method that checks whether or not a rationale dialog is shown code 1 and code 2

## Code and logs
code 0:
EasyPermissions.requestPermissions(this,
                                                   "To function properly, App needs your permissions. Allow permissions for App",
                                                   RC_REQUIRED_PERM,
                                                   REQUESTED_PERMISSIONS_ON_START);

code 1:
  
![1](https://user-images.githubusercontent.com/35255808/34714454-c54dce0c-f529-11e7-8523-fceeb434940a.png)

code 2:

![2](https://user-images.githubusercontent.com/35255808/34714468-d4b8368e-f529-11e7-94e4-b16bce47f599.png)

// TODO(you): show the code that produces the problem,
execute code 0 in onStart() ex. go to background and returning to application more than 1 time

**Comment by samtstern** [comment] 2018-01-09 16:00
@mgolebiowski95 can you show your `onStart` method?

**Comment by mgolebiowski95** [comment] 2018-01-10 10:31
![3](https://user-images.githubusercontent.com/35255808/34767974-d3b553c2-f5f9-11e7-9952-395f562da3b4.jpg)

**Comment by mgolebiowski95** [comment] 2018-01-10 13:01
or run this code and change orientation a few times

**Comment by mgolebiowski95** [comment] 2018-01-10 13:04
my requested permisison
![4](https://user-images.githubusercontent.com/35255808/34774316-2790d54c-f60f-11e7-9558-8e0274729a72.png)

**Comment by mgolebiowski95** [comment] 2018-01-10 13:29
You can too add to library method cheching android permission dialog is actually showing. In onCreate() bundle savedInstanceState key="android:hasCurrentPermissionsRequest" which contains this value.

**Comment by mgolebiowski95** [comment] 2018-01-10 13:30
I found quite accidentally :-)

**Comment by mgolebiowski95** [comment] 2018-01-10 13:46
![5](https://user-images.githubusercontent.com/35255808/34775864-f752c286-f614-11e7-8245-6f74ca309928.png)

**Comment by samtstern** [comment] 2018-01-10 16:19
@mgolebiowski95 huh that's a cool tip about `android:hasCurrentPermissionsRequest`.  Thanks!

Can you show the crash logs you're getting?  Also is your Activity a descendant of `AppCompatActivity`?

**Comment by mgolebiowski95** [comment] 2018-01-11 08:02
I hadn't crash. This is my simple test https://github.com/mgolebiowski95/easypermissionstest.

problem: stack rationale dialog

- clear application data -> grand first permission, other deny ->  close appsetting dialog -> rotate phone a few times

- clear application data -> grand first permission, other deny -> rotate phone a few times (rationale dialog stack below appsetting dialog)

**Comment by samtstern** [comment] 2018-01-11 16:38
@mgolebiowski95 thanks for the code, I can confirm that in your situation the dialog does stack.  There are two action items here:

  * This library should make an attempt to not show the rationale dialog if one is already showing.
  * Your app probably should not show the dialog on `onStart`, the Android UX guidelines for permissions
     requests say to show the request in response to a user action (button click, etc)

**Comment by samtstern** [comment] 2018-01-11 17:58
#195 will fix this issue

**Comment by samtstern** [comment] 2018-01-12 16:24
This issue has been fixed and released in version `1.1.2`

**Closed by samtstern** 2018-01-12 16:24 UTC
Labels: bug, fix-implemented

**Comment by LolWalid** [comment] 2019-03-21 16:38
I have a similar bug in version `1.2.0` and not in `1.1.2`.

Looks like easypermission is keeping reference to the Fragment after rotation

But I don't get why if I rotate only once, it doesn't crash.
