### ISSUE TITLE
Calling `EasyPermissions.requestPermissions` in `onPermissionsDenied` doesn't show permission dialog.

### ISSUE THREAD

**Issue by omar753sahl** [googlesamples/easypermissions#240] opened 2018-08-14 14:08 UTC
## Basic Information

Device type: Samsung J7 2016
OS version: 7.0
EasyPermissions version: 1.3.0
 
Calling `EasyPermissions.requestPermissions` in `onPermissionsDenied` doesn't show permission dialog.

Is this the intended behavior or am I missing something?
I expected to see another permission dialog.

**Comment by omar753sahl** [comment] 2018-08-14 14:36
UPDATE: I downgraded to version 1.1.1 and it worked as expected.

**Comment by SUPERCILEX** [comment] 2018-08-14 16:13
See https://github.com/googlesamples/easypermissions/issues/204#issuecomment-412204799, I can't reproduce it so getting a sample would be great.

**Comment by samtstern** [comment] 2018-08-14 17:56
Going to mark this a duplicate of #204 but @omar753sahl let's keep discussing over there if you are willing!

**Closed by samtstern** 2018-08-14 17:56 UTC
