### ISSUE TITLE
How to deny the request dialog with rational string by easy permission

### ISSUE THREAD

**Issue by Kevin-Kuloth** [googlesamples/easypermissions#69] opened 2016-12-29 07:06 UTC
I don't want the alert dialog shown by the easy permission before the actual permission dialog.

**Comment by samtstern** [comment] 2017-01-03 16:02
@Kevin-Kuloth the alert dialog is only shown before the permission dialog if the user has denied the permission at least once. This is because the Android permissions system tells us we should show rationale, and this is considered best practice.

I believe this is working as intended so I will close the issue, please re-open and add details if I have misunderstood.

**Closed by samtstern** 2017-01-03 16:02 UTC

**Comment by Codepeaker** [comment] 2019-01-09 08:34
It's not intuitive, just simple text and two buttons because of that user will mostly cancel and move on.
We should either provide a custom XML and a flag to enable or disable or completely remove it.
