### ISSUE TITLE
No callback when using in android.app.Fragment

### ISSUE THREAD

**Issue by phcannesson** [googlesamples/easypermissions#57] opened 2016-11-09 16:19 UTC
When using the library on an android.app.Fragment, I'm not receiving any callback if the rationale has been shown before the permission request. It works well if the rationale is not displayed.

I've taken a look at the code and it looks like the problem comes from the click listener for the rationale dialog, created here in RationaleDialogClickListener.java : 

```
@RequiresApi(api = Build.VERSION_CODES.HONEYCOMB)
    RationaleDialogClickListener(RationaleDialogFragment dialogFragment,
                                 RationaleDialogConfig config,
                                 EasyPermissions.PermissionCallbacks callbacks) {

        mHost = dialogFragment.getActivity();
        mConfig = config;
        mCallbacks = callbacks;
    }
```
We are setting the host as the activity, not the fragment itself.
But then this host is used to perform another permission request, but not using a fragment host will makes it so the activity will not propagate the result to fragments.

What do you think ? Am I missing something ?

**Comment by samtstern** [comment] 2016-11-10 18:06
@phcannesson this sounds like it could be a real bug, do you want to try to fix it and send a PR?  Would be happy to review.

I do remember there was some reason for needing to make the host the Activity, but I can't remember what it was right now.

**Comment by j-garin** [comment] 2016-11-11 15:53
Hi. I have bumped into the very same issue.
However, I think it is caused by a different part of code (see below). By the looks of it, using android.app.Fragment requires Marshmallow. Is there any reason behind this or it was meant to be Honeycomb?

Here's a piece of EasyPermissions.java
```
    private static void checkCallingObjectSuitability(@Nullable Object object) {
        if (object == null) {
            throw new NullPointerException("Activity or Fragment should not be null");
        }
        // Make sure Object is an Activity or Fragment
        boolean isActivity = object instanceof android.app.Activity;
        boolean isSupportFragment = object instanceof android.support.v4.app.Fragment;
        boolean isAppFragment = object instanceof android.app.Fragment;
        boolean isMinSdkM = Build.VERSION.SDK_INT >= Build.VERSION_CODES.M;
        if (!(isSupportFragment || isActivity || (isAppFragment && isMinSdkM))) {
            if (isAppFragment) {
                throw new IllegalArgumentException(
                        "Target SDK needs to be greater than 23 if caller is android.app.Fragment");
            } else {
                throw new IllegalArgumentException("Caller must be an Activity or a Fragment.");
            }
        }
    }
```

**Comment by samtstern** [comment] 2016-11-11 15:54
@j-garin the reason for the Marshmallow check is because runtime permissions are irrelevant below that.  The permission checks should always return true.

**Comment by j-garin** [comment] 2016-11-11 16:00
@samtstern not sure why it applies only to android.appFragment, but not support fragments and activities?

**Comment by phcannesson** [comment] 2016-11-14 15:54
@samtstern I'll create a PR as soon as I can.

**Comment by samtstern** [comment] 2016-12-06 18:46
This is fixed in `master`.  Thanks @phcannesson

**Closed by samtstern** 2016-12-06 18:46 UTC

**Comment by j-garin** [comment] 2016-12-08 13:09
Will there be a library update with this fix?

**Comment by samtstern** [comment] 2016-12-09 16:31
@j-garin I normally wait until a few bugfixes in a row have landed and then bundle them all up into a release.  

Have you tried installing from `master`?  If you're having problems with that, let me know.

**Comment by j-garin** [comment] 2016-12-12 10:03
@samtstern it's not critical. I will wait for the next release. Thank you.
