### ISSUE TITLE
Annoteated methods not run when method is in super class

### ISSUE THREAD

**Issue by splangi** [googlesamples/easypermissions#84] opened 2017-02-16 09:49 UTC
`for (Method method : clazz.getDeclaredMethods()) {
            if (method.isAnnotationPresent(AfterPermissionGranted.class)) {
               /* more code */
            }
        }`

When using a base class (e.g. BaseFragment) which has annoteated AfterPermissionGranted methods  then these are not run. The reason seems to be that clazz.getDeclaredMethods() only returns the methods which are declared in the class itself and not the superclass ones. 

This might be intented behaviour, but just wanted to check.

**Comment by samtstern** [comment] 2017-02-16 16:19
@splangi that is in fact the current intended behavior but if you want to submit a pull request to change this behavior I see no problem with running annotated methods in super classes.

**Comment by samtstern** [comment] 2017-02-22 16:18
A fix for this has been merged, will be in the next release.

**Closed** 2017-02-22 16:18 UTC
Labels: enhancement
